# Generated by Django 4.1.3 on 2022-11-12 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('types', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=25)),
                ('title', models.TextField(max_length=150)),
                ('content', models.TextField(max_length=1500)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('support', models.IntegerField()),
                ('report', models.IntegerField()),
                ('comments_json', models.JSONField(default={'available': 0})),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.TextField(max_length=1500)),
                ('address', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('disorder_type', models.CharField(max_length=30)),
            ],
        ),
    ]
