# Generated by Django 4.1.3 on 2022-11-11 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25, unique=True)),
                ('title', models.TextField(max_length=150)),
                ('content', models.TextField(max_length=1500)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('support', models.IntegerField()),
                ('report', models.IntegerField()),
                ('comments_json', models.JSONField(default={'available': 0})),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
